### PR TITLE
Adding Array Reverse in Group Algorithm

### PR DESCRIPTION
**Pull request by xyther14**
Array Reverse in Group Algorithm by xyther14

### CODE REVIEW

**Review by sparsh-99 — CHANGES_REQUESTED** [review]
@xyther14, Also delete these modules, vcs, and these additional files also. Just keep the main code file in the PR

**Comment by xyther14** [comment]
> @xyther14, Also delete these modules, vcs, and these additional files also. Just keep the main code file in the PR

There's only 1 file now. I deleted the .idea directory

**Review by sparsh-99 — APPROVED** [review]
Now, its good to go @xyther14

**Comment by sparsh-99** [comment]
@xyther14, I mentioned that PR should be in General folder only

**Comment by xyther14** [comment]
When I saw the issue, it wasn't mentioned. You must have changed it afterwards. Should I PR again?

**Comment by sparsh-99** [comment]
No No, Just change the folder of the PR

**Comment by sparsh-99** [comment]
Just made a commit with this file in General folder

**Pull request merged**
