### PR TITLE
adding armstrong number in c

### PR DESCRIPTION
**Pull request by rohansharma4050**
please add this pr for hacktoberfest2021

### CODE REVIEW

**Review by sparsh-99 — CHANGES_REQUESTED** [review]
Just beautify this code. Do proper indentation. Otherwise, the code looks fine to be me.

**Comment by rohansharma4050** [comment]
@sparsh-99  made the requested changes added the spaces and beautified the code as well !

**Review by sparsh-99 — COMMENTED** [review]
Do 1 thing, just search on Google for "Code beautifier in C". Copy your code there and beautify it. 
Then, do another commit with that code.
Thank you

**Comment by rohansharma4050** [comment]
@sparsh-99 is it fine now?

**Review by sparsh-99 — APPROVED** [review]
That's what I am talking about.

**Pull request merged**
